
region: tjobs_cleaner

# Задержка восстановления в секундах.
# Можно указать точное число: 10
# Или диапазон: 10r15 (рандом от 10 до 15 включительно)
respawn-delay: 10r15

# Список растений, которые отслеживаются
plants:
  WHEAT:
    reward: "5r10"
  CARROTS:
    reward: "2r4"
  POTATOES:
    reward: "3"


reward:
  # Переменные {player} {amount}
  command: "eco give {player} {amount}"