name: TCleanerJob
version: '1.2'
main: ru.taiufun.tCleanerJob.TCleanerJob
depend: [WorldGuard, WorldEdit]
api-version: 1.16
commands:
  tcleanerjob:
    description: Перезагрузка конфига
    usage: /<command> reload
    permission: tcleanerjob.reload
    aliases:
      - tcj
      - tcleaner
      - tcleanjob
      - tclean